spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: service-provider
          uri: lb://PROVIDER-APP
          predicates:
            - Path=/**



eureka:
  client:
    service-url:
      # Register self
      defaultZone: http://127.0.0.1:12345/eureka
  instance:
    instanceId: ${spring.cloud.client.ip-address}:8080