spring:
  application:
    name: eureka-application


server:
  port: 12345

# Eureka 客户端连接配置
eureka:
  client:
    service-url:
      # Register self
      defaultZone: http://127.0.0.1:${server.port}/eureka
    # Do not fetch itself
    fetch-registry: false
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
